Repository GTBitsOfGood/website, pull requests merged in 2020-03, with the labels that each got.

#42 Update font to Open Sans
  src/components/GetInvolvedBtn.svelte
  src/components/InfoCard/Container.svelte
  src/components/about-us/MilestonesSection.svelte
  src/components/join/Footer.svelte
  src/components/join/Role.svelte
  src/components/landing/Heading.svelte
  src/components/landing/QuotesSection/index.svelte
  src/routes/_error.svelte
  src/routes/contact-submitted.svelte
  src/routes/contact.svelte
  src/routes/join.svelte
  static/fonts/VisbyCF-Bold.ttf
  static/fonts/VisbyCF-Bold.woff
  static/global.css
Labels: enhancement, p1, visuals 💅

#45 Homepage renovations
  rollup-plugin-content-loader.js
  src/components/landing/BigLogo.svelte
  src/components/landing/BuildingSection.svelte
  src/components/landing/ConnectingSection.svelte
  src/components/landing/Heading.svelte
  src/routes/index.svelte
  static/images/bog-logo.svg
  static/images/building-artwork-back.svg
  static/images/building-artwork-front.png
  static/images/connecting-artwork-back.svg
  static/images/connecting-artwork-front.png
  static/images/logo-placeholder-image.jpg
Labels: enhancement, p3, visuals 💅

#50 Clean up and DRY BigLogo.svelte
  src/components/landing/BigLogo.svelte
Labels: bug, p3, visuals 💅

#46 add footer
  rollup-plugin-content-loader.js
  src/components/Footer.svelte
  src/routes/_layout.svelte
  src/routes/index.svelte
Labels: enhancement, p3
